/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHESnakeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getLongestLength"
      | "hasPlayed"
      | "updateLength"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLongestLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlayed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLength",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLongestLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasPlayed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLength",
    data: BytesLike
  ): Result;
}

export interface FHESnake extends BaseContract {
  connect(runner?: ContractRunner | null): FHESnake;
  waitForDeployment(): Promise<this>;

  interface: FHESnakeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getLongestLength: TypedContractMethod<
    [player: AddressLike],
    [string],
    "view"
  >;

  hasPlayed: TypedContractMethod<[player: AddressLike], [boolean], "view">;

  updateLength: TypedContractMethod<
    [encryptedLength: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLongestLength"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasPlayed"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateLength"
  ): TypedContractMethod<
    [encryptedLength: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
